package jobs

import (
	"context"
	"fmt"
	"log"
	"time"

	"worldcup-mate/internal/models"
	"worldcup-mate/internal/repositories"
	"worldcup-mate/internal/services"
)

type PostMatchSummaryJobConfig struct {
	Enabled       bool
	Interval      time.Duration
	LookbackHours time.Duration
	AutoGenerate  bool
}

var postSummaryJobCfg PostMatchSummaryJobConfig

func ConfigurePostMatchSummaryJob(cfg PostMatchSummaryJobConfig) {
	postSummaryJobCfg = cfg
}

func StartPostMatchSummaryScanner() {
	if !postSummaryJobCfg.Enabled || !postSummaryJobCfg.AutoGenerate {
		log.Println("Post-match summary scanner disabled")
		return
	}

	go func() {
		log.Printf("Post-match summary scanner started (interval: %v)", postSummaryJobCfg.Interval)
		ticker := time.NewTicker(postSummaryJobCfg.Interval)
		defer ticker.Stop()

		// Run once on startup
		runPostMatchSummaryScan()

		for range ticker.C {
			runPostMatchSummaryScan()
		}
	}()
}

func runPostMatchSummaryScan() {
	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
	defer cancel()

	since := time.Now().UTC().Add(-postSummaryJobCfg.LookbackHours)
	matches, err := repositories.ListFinishedMatchesSince(since)
	if err != nil {
		log.Printf("Post-match summary scan: query finished matches error: %v", err)
		return
	}

	for _, match := range matches {
		if err := processFinishedMatch(ctx, match); err != nil {
			log.Printf("Post-match summary failed for match %d: %v", match.ID, err)
		}
	}
}

func processFinishedMatch(ctx context.Context, match models.Match) error {
	// Check if summary already generated by looking for cached content
	cacheKey := fmt.Sprintf("ai:%s:post_match_summary:%d", services.GetAIProvider(), match.ID)
	existing, err := repositories.GetGeneratedContentByCacheKey(cacheKey)
	if err == nil && existing != nil && existing.ContentJSON != "" {
		// Already generated, only send notifications if not yet sent
		return sendPostMatchSummaryNotifications(match, false)
	}

	// Generate summary
	req := services.PostMatchSummaryRequest{
		MatchID:      match.ID,
		ForceRefresh: false,
	}
	_, err = services.GeneratePostMatchSummary(ctx, req, nil, "job")
	if err != nil {
		return fmt.Errorf("generate summary: %w", err)
	}

	// Send notifications to interested users
	return sendPostMatchSummaryNotifications(match, true)
}

func sendPostMatchSummaryNotifications(match models.Match, newSummary bool) error {
	userIDs, err := collectPostMatchTargetUsers(match.ID)
	if err != nil {
		return err
	}
	if len(userIDs) == 0 {
		return nil
	}

	title := fmt.Sprintf("赛后摘要已生成：%s %d-%d %s", match.HomeTeam.Name, *match.HomeScore, *match.AwayScore, match.AwayTeam.Name)
	content := "3 分钟了解比赛结果、积分影响和是否值得补看。"

	for _, userID := range userIDs {
		exists, err := repositories.HasUserMatchEvent(userID, match.ID, "post_match_summary")
		if err != nil || exists {
			continue
		}

		notification := &models.Notification{
			UserID:     userID,
			Title:      title,
			Content:    content,
			Type:       "post_match_summary",
			TargetType: "match",
			TargetID:   match.ID,
		}
		if err := repositories.CreateNotification(notification); err != nil {
			log.Printf("Create post-match summary notification failed for user %d match %d: %v", userID, match.ID, err)
			continue
		}
		_ = repositories.CreateUserMatchEvent(userID, match.ID, "post_match_summary")
	}
	return nil
}

func collectPostMatchTargetUsers(matchID uint) ([]uint, error) {
	seen := make(map[uint]bool)
	var allIDs []uint

	favIDs, err := repositories.ListUserIDsByFavoriteMatch(matchID)
	if err != nil {
		return nil, err
	}
	for _, id := range favIDs {
		if !seen[id] {
			seen[id] = true
			allIDs = append(allIDs, id)
		}
	}

	remindIDs, err := repositories.ListUserIDsByMatchReminders(matchID)
	if err != nil {
		return nil, err
	}
	for _, id := range remindIDs {
		if !seen[id] {
			seen[id] = true
			allIDs = append(allIDs, id)
		}
	}

	return allIDs, nil
}
