package services

import (
	"worldcup-mate/internal/database"
	"worldcup-mate/internal/models"
)

type localizedTeam struct {
	Name      string
	Continent string
}

var localizedTeams = map[string]localizedTeam{
	// 2026 世界杯参赛球队
	"ALG": {Name: "阿尔及利亚", Continent: "非洲"},
	"ARG": {Name: "阿根廷", Continent: "南美洲"},
	"AUS": {Name: "澳大利亚", Continent: "大洋洲"},
	"AUT": {Name: "奥地利", Continent: "欧洲"},
	"BEL": {Name: "比利时", Continent: "欧洲"},
	"BOL": {Name: "玻利维亚", Continent: "南美洲"},
	"BIH": {Name: "波黑", Continent: "欧洲"},
	"BRA": {Name: "巴西", Continent: "南美洲"},
	"BUL": {Name: "保加利亚", Continent: "欧洲"},
	"CAN": {Name: "加拿大", Continent: "北美洲"},
	"CHI": {Name: "智利", Continent: "南美洲"},
	"CHN": {Name: "中国", Continent: "亚洲"},
	"COL": {Name: "哥伦比亚", Continent: "南美洲"},
	"CRC": {Name: "哥斯达黎加", Continent: "北美洲"},
	"CRO": {Name: "克罗地亚", Continent: "欧洲"},
	"CUW": {Name: "库拉索", Continent: "北美洲"},
	"CUR": {Name: "库拉索", Continent: "北美洲"},
	"CIV": {Name: "科特迪瓦", Continent: "非洲"},
	"CMR": {Name: "喀麦隆", Continent: "非洲"},
	"ALB": {Name: "阿尔巴尼亚", Continent: "欧洲"},
	"ARM": {Name: "亚美尼亚", Continent: "欧洲"},
	"AZE": {Name: "阿塞拜疆", Continent: "亚洲"},
	"BLR": {Name: "白俄罗斯", Continent: "欧洲"},
	"CYM": {Name: "开曼群岛", Continent: "北美洲"},
	"DMA": {Name: "多米尼克", Continent: "北美洲"},
	"GRN": {Name: "格林纳达", Continent: "北美洲"},
	"GUY": {Name: "圭亚那", Continent: "南美洲"},
	"KIR": {Name: "基里巴斯", Continent: "大洋洲"},
	"LAO": {Name: "老挝", Continent: "亚洲"},
	"LIE": {Name: "列支敦士登", Continent: "欧洲"},
	"MDA": {Name: "摩尔多瓦", Continent: "欧洲"},
	"MYA": {Name: "缅甸", Continent: "亚洲"},
	"NEP": {Name: "尼泊尔", Continent: "亚洲"},
	"PNG": {Name: "巴布亚新几内亚", Continent: "大洋洲"},
	"SKN": {Name: "圣基茨和尼维斯", Continent: "北美洲"},
	"LCA": {Name: "圣卢西亚", Continent: "北美洲"},
	"VCT": {Name: "圣文森特和格林纳丁斯", Continent: "北美洲"},
	"SOL": {Name: "所罗门群岛", Continent: "大洋洲"},
	"TAH": {Name: "大溪地", Continent: "大洋洲"},
	"TJK": {Name: "塔吉克斯坦", Continent: "亚洲"},
	"TKM": {Name: "土库曼斯坦", Continent: "亚洲"},
	"TLS": {Name: "东帝汶", Continent: "亚洲"},
	"TUV": {Name: "图瓦卢", Continent: "大洋洲"},
	"VAN": {Name: "瓦努阿图", Continent: "大洋洲"},
	"CZE": {Name: "捷克", Continent: "欧洲"},
	"DEN": {Name: "丹麦", Continent: "欧洲"},
	"ECU": {Name: "厄瓜多尔", Continent: "南美洲"},
	"EGY": {Name: "埃及", Continent: "非洲"},
	"ENG": {Name: "英格兰", Continent: "欧洲"},
	"ESP": {Name: "西班牙", Continent: "欧洲"},
	"FRA": {Name: "法国", Continent: "欧洲"},
	"GAB": {Name: "加蓬", Continent: "非洲"},
	"GAM": {Name: "冈比亚", Continent: "非洲"},
	"GEO": {Name: "格鲁吉亚", Continent: "欧洲"},
	"GER": {Name: "德国", Continent: "欧洲"},
	"GHA": {Name: "加纳", Continent: "非洲"},
	"GRE": {Name: "希腊", Continent: "欧洲"},
	"GUA": {Name: "危地马拉", Continent: "北美洲"},
	"GUI": {Name: "几内亚", Continent: "非洲"},
	"HAI": {Name: "海地", Continent: "北美洲"},
	"HON": {Name: "洪都拉斯", Continent: "北美洲"},
	"HUN": {Name: "匈牙利", Continent: "欧洲"},
	"IDN": {Name: "印度尼西亚", Continent: "亚洲"},
	"IND": {Name: "印度", Continent: "亚洲"},
	"IRN": {Name: "伊朗", Continent: "亚洲"},
	"IRQ": {Name: "伊拉克", Continent: "亚洲"},
	"IRL": {Name: "爱尔兰", Continent: "欧洲"},
	"ISL": {Name: "冰岛", Continent: "欧洲"},
	"ISR": {Name: "以色列", Continent: "欧洲"},
	"ITA": {Name: "意大利", Continent: "欧洲"},
	"JAM": {Name: "牙买加", Continent: "北美洲"},
	"JOR": {Name: "约旦", Continent: "亚洲"},
	"JPN": {Name: "日本", Continent: "亚洲"},
	"KAZ": {Name: "哈萨克斯坦", Continent: "亚洲"},
	"KEN": {Name: "肯尼亚", Continent: "非洲"},
	"KOR": {Name: "韩国", Continent: "亚洲"},
	"KOS": {Name: "科索沃", Continent: "欧洲"},
	"KSA": {Name: "沙特阿拉伯", Continent: "亚洲"},
	"LBN": {Name: "黎巴嫩", Continent: "亚洲"},
	"LIB": {Name: "利比亚", Continent: "非洲"},
	"LUX": {Name: "卢森堡", Continent: "欧洲"},
	"MAD": {Name: "马达加斯加", Continent: "非洲"},
	"MAR": {Name: "摩洛哥", Continent: "非洲"},
	"MEX": {Name: "墨西哥", Continent: "北美洲"},
	"MLI": {Name: "马里", Continent: "非洲"},
	"MNE": {Name: "黑山", Continent: "欧洲"},
	"MNT": {Name: "蒙特塞拉特", Continent: "北美洲"},
	"NED": {Name: "荷兰", Continent: "欧洲"},
	"NGA": {Name: "尼日利亚", Continent: "非洲"},
	"NIG": {Name: "尼日尔", Continent: "非洲"},
	"NOR": {Name: "挪威", Continent: "欧洲"},
	"NZL": {Name: "新西兰", Continent: "大洋洲"},
	"OMA": {Name: "阿曼", Continent: "亚洲"},
	"PAK": {Name: "巴基斯坦", Continent: "亚洲"},
	"PAN": {Name: "巴拿马", Continent: "北美洲"},
	"PAR": {Name: "巴拉圭", Continent: "南美洲"},
	"PER": {Name: "秘鲁", Continent: "南美洲"},
	"PHI": {Name: "菲律宾", Continent: "亚洲"},
	"POL": {Name: "波兰", Continent: "欧洲"},
	"POR": {Name: "葡萄牙", Continent: "欧洲"},
	"QAT": {Name: "卡塔尔", Continent: "亚洲"},
	"ROM": {Name: "罗马尼亚", Continent: "欧洲"},
	"RSA": {Name: "南非", Continent: "非洲"},
	"RUS": {Name: "俄罗斯", Continent: "欧洲"},
	"SCO": {Name: "苏格兰", Continent: "欧洲"},
	"SEN": {Name: "塞内加尔", Continent: "非洲"},
	"SER": {Name: "塞尔维亚", Continent: "欧洲"},
	"SIN": {Name: "新加坡", Continent: "亚洲"},
	"SLV": {Name: "萨尔瓦多", Continent: "北美洲"},
	"SRB": {Name: "塞尔维亚", Continent: "欧洲"},
	"SUI": {Name: "瑞士", Continent: "欧洲"},
	"SUR": {Name: "苏里南", Continent: "南美洲"},
	"SWE": {Name: "瑞典", Continent: "欧洲"},
	"THA": {Name: "泰国", Continent: "亚洲"},
	"TOG": {Name: "多哥", Continent: "非洲"},
	"TRI": {Name: "特立尼达和多巴哥", Continent: "北美洲"},
	"TUN": {Name: "突尼斯", Continent: "非洲"},
	"TUR": {Name: "土耳其", Continent: "欧洲"},
	"UAE": {Name: "阿联酋", Continent: "亚洲"},
	"UGA": {Name: "乌干达", Continent: "非洲"},
	"UKR": {Name: "乌克兰", Continent: "欧洲"},
	"URU": {Name: "乌拉圭", Continent: "南美洲"},
	"USA": {Name: "美国", Continent: "北美洲"},
	"UZB": {Name: "乌兹别克斯坦", Continent: "亚洲"},
	"VEN": {Name: "委内瑞拉", Continent: "南美洲"},
	"WAL": {Name: "威尔士", Continent: "欧洲"},
	"YEM": {Name: "也门", Continent: "亚洲"},
	"ZAM": {Name: "赞比亚", Continent: "非洲"},
	"ZIM": {Name: "津巴布韦", Continent: "非洲"},
	"CPV": {Name: "佛得角", Continent: "非洲"},
	"ERI": {Name: "厄立特里亚", Continent: "非洲"},
	"BEN": {Name: "贝宁", Continent: "非洲"},
	"BFA": {Name: "布基纳法索", Continent: "非洲"},
	"BDI": {Name: "布隆迪", Continent: "非洲"},
	"CGO": {Name: "刚果共和国", Continent: "非洲"},
	"COD": {Name: "刚果民主共和国", Continent: "非洲"},
	"DJI": {Name: "吉布提", Continent: "非洲"},
	"GNQ": {Name: "赤道几内亚", Continent: "非洲"},
	"ETH": {Name: "埃塞俄比亚", Continent: "非洲"},
	"LES": {Name: "莱索托", Continent: "非洲"},
	"LBR": {Name: "利比里亚", Continent: "非洲"},
	"MWI": {Name: "马拉维", Continent: "非洲"},
	"MRI": {Name: "毛里求斯", Continent: "非洲"},
	"MOZ": {Name: "莫桑比克", Continent: "非洲"},
	"NAM": {Name: "纳米比亚", Continent: "非洲"},
	"RWA": {Name: "卢旺达", Continent: "非洲"},
	"SAO": {Name: "圣多美和普林西比", Continent: "非洲"},
	"SEY": {Name: "塞舌尔", Continent: "非洲"},
	"SLE": {Name: "塞拉利昂", Continent: "非洲"},
	"SWZ": {Name: "斯威士兰", Continent: "非洲"},
	"TAN": {Name: "坦桑尼亚", Continent: "非洲"},
	"ZAI": {Name: "扎伊尔", Continent: "非洲"},
}

func localizeTeam(code, fallbackName string) (name, continent string) {
	// First try by FIFA code
	if item, ok := localizedTeams[code]; ok {
		return item.Name, item.Continent
	}
	// Then try by English name
	if chineseName, ok := englishToChinese[fallbackName]; ok {
		return chineseName, ""
	}
	return fallbackName, ""
}

// English to Chinese team name mapping for teams that might be stored with English names
var englishToChinese = map[string]string{
	// 亚洲
	"China":           "中国",
	"Japan":           "日本",
	"South Korea":     "韩国",
	"North Korea":     "朝鲜",
	"Iran":            "伊朗",
	"Iraq":            "伊拉克",
	"Saudi Arabia":    "沙特阿拉伯",
	"Qatar":           "卡塔尔",
	"UAE":             "阿联酋",
	"Oman":            "阿曼",
	"Jordan":          "约旦",
	"Lebanon":         "黎巴嫩",
	"Syria":           "叙利亚",
	"Palestine":       "巴勒斯坦",
	"Kuwait":          "科威特",
	"Bahrain":         "巴林",
	"Yemen":           "也门",
	"Afghanistan":     "阿富汗",
	"India":           "印度",
	"Pakistan":         "巴基斯坦",
	"Bangladesh":      "孟加拉国",
	"Sri Lanka":       "斯里兰卡",
	"Nepal":           "尼泊尔",
	"Bhutan":          "不丹",
	"Maldives":        "马尔代夫",
	"Thailand":        "泰国",
	"Vietnam":         "越南",
	"Malaysia":        "马来西亚",
	"Indonesia":       "印度尼西亚",
	"Philippines":     "菲律宾",
	"Singapore":       "新加坡",
	"Myanmar":         "缅甸",
	"Cambodia":        "柬埔寨",
	"Laos":            "老挝",
	"Brunei":          "文莱",
	"Timor-Leste":     "东帝汶",
	"Chinese Taipei":  "中华台北",
	"Hong Kong":       "中国香港",
	"Macau":           "中国澳门",
	"Kazakhstan":      "哈萨克斯坦",
	"Uzbekistan":      "乌兹别克斯坦",
	"Kyrgyzstan":      "吉尔吉斯斯坦",
	"Tajikistan":      "塔吉克斯坦",
	"Turkmenistan":    "土库曼斯坦",

	// 欧洲
	"England":         "英格兰",
	"Scotland":        "苏格兰",
	"Wales":           "威尔士",
	"Northern Ireland": "北爱尔兰",
	"Republic of Ireland": "爱尔兰",
	"France":          "法国",
	"Germany":         "德国",
	"Spain":           "西班牙",
	"Portugal":        "葡萄牙",
	"Italy":           "意大利",
	"Netherlands":     "荷兰",
	"Belgium":         "比利时",
	"Switzerland":     "瑞士",
	"Austria":         "奥地利",
	"Poland":          "波兰",
	"Czech Republic":  "捷克",
	"Denmark":         "丹麦",
	"Sweden":          "瑞典",
	"Norway":          "挪威",
	"Finland":         "芬兰",
	"Iceland":         "冰岛",
	"Greece":          "希腊",
	"Turkey":          "土耳其",
	"Croatia":         "克罗地亚",
	"Serbia":          "塞尔维亚",
	"Bulgaria":        "保加利亚",
	"Romania":         "罗马尼亚",
	"Hungary":         "匈牙利",
	"Ukraine":         "乌克兰",
	"Belarus":         "白俄罗斯",
	"Russia":          "俄罗斯",
	"Slovakia":        "斯洛伐克",
	"Slovenia":        "斯洛文尼亚",
	"Albania":         "阿尔巴尼亚",
	"Bosnia and Herzegovina": "波黑",
	"Montenegro":      "黑山",
	"North Macedonia": "北马其顿",
	"Kosovo":          "科索沃",
	"Moldova":         "摩尔多瓦",
	"Lithuania":       "立陶宛",
	"Latvia":          "拉脱维亚",
	"Estonia":         "爱沙尼亚",
	"Georgia":         "格鲁吉亚",
	"Armenia":         "亚美尼亚",
	"Azerbaijan":      "阿塞拜疆",
	"Luxembourg":       "卢森堡",
	"Malta":           "马耳他",
	"Cyprus":          "塞浦路斯",
	"Liechtenstein":   "列支敦士登",
	"San Marino":      "圣马力诺",
	"Andorra":         "安道尔",
	"Monaco":          "摩纳哥",
	"Vatican City":    "梵蒂冈",

	// 南美洲
	"Argentina":       "阿根廷",
	"Brazil":          "巴西",
	"Uruguay":         "乌拉圭",
	"Colombia":        "哥伦比亚",
	"Chile":           "智利",
	"Paraguay":        "巴拉圭",
	"Peru":            "秘鲁",
	"Ecuador":         "厄瓜多尔",
	"Bolivia":         "玻利维亚",
	"Venezuela":       "委内瑞拉",
	"Guyana":          "圭亚那",
	"Suriname":        "苏里南",

	// 北美洲
	"USA":             "美国",
	"United States":   "美国",
	"Canada":          "加拿大",
	"Mexico":          "墨西哥",
	"Costa Rica":      "哥斯达黎加",
	"Honduras":        "洪都拉斯",
	"Panama":          "巴拿马",
	"Jamaica":         "牙买加",
	"Trinidad and Tobago": "特立尼达和多巴哥",
	"Haiti":           "海地",
	"Cuba":            "古巴",
	"El Salvador":     "萨尔瓦多",
	"Guatemala":       "危地马拉",
	"Nicaragua":       "尼加拉瓜",
	"Dominican Republic": "多米尼加",
	"Belize":          "伯利兹",
	"Barbados":        "巴巴多斯",
	"Bahamas":         "巴哈马",
	"Antigua and Barbuda": "安提瓜和巴布达",
	"Saint Kitts and Nevis": "圣基茨和尼维斯",
	"Saint Lucia":     "圣卢西亚",
	"Saint Vincent and the Grenadines": "圣文森特和格林纳丁斯",
	"Grenada":         "格林纳达",
	"Dominica":        "多米尼克",

	// 非洲
	"Morocco":         "摩洛哥",
	"Tunisia":         "突尼斯",
	"Algeria":         "阿尔及利亚",
	"Egypt":           "埃及",
	"Nigeria":         "尼日利亚",
	"Senegal":         "塞内加尔",
	"Ghana":           "加纳",
	"Cameroon":        "喀麦隆",
	"Ivory Coast":     "科特迪瓦",
	"Côte d'Ivoire":   "科特迪瓦",
	"Mali":            "马里",
	"Burkina Faso":    "布基纳法索",
	"DR Congo":        "刚果民主共和国",
	"South Africa":    "南非",
	"Cape Verde":      "佛得角",
	"Cape Verde Islands": "佛得角",
	"Equatorial Guinea": "赤道几内亚",
	"Gabon":           "加蓬",
	"Gambia":          "冈比亚",
	"Guinea":          "几内亚",
	"Guinea-Bissau":   "几内亚比绍",
	"Kenya":           "肯尼亚",
	"Libya":           "利比亚",
	"Madagascar":      "马达加斯加",
	"Mauritius":       "毛里求斯",
	"Mozambique":      "莫桑比克",
	"Namibia":         "纳米比亚",
	"Niger":           "尼日尔",
	"Rwanda":          "卢旺达",
	"Somalia":         "索马里",
	"Sudan":           "苏丹",
	"South Sudan":     "南苏丹",
	"Tanzania":        "坦桑尼亚",
	"Togo":            "多哥",
	"Uganda":          "乌干达",
	"Zambia":          "赞比亚",
	"Zimbabwe":        "津巴布韦",
	"Benin":           "贝宁",
	"Botswana":        "博茨瓦纳",
	"Burundi":         "布隆迪",
	"Central African Republic": "中非共和国",
	"Chad":            "乍得",
	"Comoros":         "科摩罗",
	"Congo":           "刚果共和国",
	"Djibouti":        "吉布提",
	"Eritrea":         "厄立特里亚",
	"Eswatini":        "斯威士兰",
	"Ethiopia":        "埃塞俄比亚",
	"Lesotho":         "莱索托",
	"Liberia":         "利比里亚",
	"Malawi":          "马拉维",
	"Mauritania":      "毛里塔尼亚",
	"Réunion":         "留尼汪",
	"São Tomé and Príncipe": "圣多美和普林西比",
	"Seychelles":      "塞舌尔",
	"Sierra Leone":    "塞拉利昂",

	// 大洋洲
	"Australia":       "澳大利亚",
	"New Zealand":     "新西兰",
	"Papua New Guinea": "巴布亚新几内亚",
	"Fiji":            "斐济",
	"Solomon Islands": "所罗门群岛",
	"Vanuatu":         "瓦努阿图",
	"Samoa":           "萨摩亚",
	"Tonga":           "汤加",
	"Kiribati":        "基里巴斯",
	"Marshall Islands": "马绍尔群岛",
	"Micronesia":      "密克罗尼西亚",
	"Nauru":           "瑙鲁",
	"Palau":           "帕劳",
	"Tuvalu":          "图瓦卢",
}

func localizeTeamByEnglishName(englishName string) (string, string) {
	if chineseName, ok := englishToChinese[englishName]; ok {
		return chineseName, ""
	}
	return "", ""
}

func UpdateAllTeamNames() error {
	var teams []models.Team
	if err := database.DB.Find(&teams).Error; err != nil {
		return err
	}
	for _, team := range teams {
		updated := false
		// Try by FIFA code first
		if item, ok := localizedTeams[team.FIFACode]; ok {
			if team.Name != item.Name || team.Continent != item.Continent {
				team.Name = item.Name
				team.Continent = item.Continent
				updated = true
			}
		} else if name, continent := localizeTeamByEnglishName(team.Name); name != "" {
			// Try by English name if FIFA code not found
			if team.Name != name {
				team.Name = name
				if continent != "" {
					team.Continent = continent
				}
				updated = true
			}
		}
		if updated {
			database.DB.Save(&team)
		}
	}
	return nil
}
